[build]
  # Comando que gera a versão final do seu site
  command = "npm run build"
  
  # Pasta onde ficam os arquivos prontos (geralmente 'dist' para Vite ou 'build' para React)
  publish = "dist"

[[redirects]]
  # Isso evita erros 404 ao atualizar a página em apps de página única (SPA)
  from = "/*"
  to = "/index.html"
  status = 200